package webapp;
public enum Errorcodes {
	BEREITS_RESERVIERT,
	BEREITS_VERKAUFT,
	RESERVIERUNG_NICHT_MOEGLICH,
	UNGUELTIGER_NAME,
	UNGUELTIGE_SITZNUMMER,
	MUSS_RESERVIERT_SEIN,
	STORNIERUNG_FREIEN_TICKETS,
	OPERATION_NICHT_GUELTIG,
	FELDER_NICHT_AUSGEFUELLT
}
